import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "../components/Header";
import Footer from "../components/Footer";
import Activiybar from "../components/Activitybar";
import Explore from "../components/Explore";
import Headermain from "../components/Headermain";
import { useStore } from "zustand";


export const metadata: Metadata = {

  title: "Arezoo Amiri Ayobloo",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>){
  return (
    
    <html lang="en">
      <body className={` antialiased min-h-screen max-h-screen text-fontcolor`} >

        <div className="  h-screen  ">
          <Header />
          <div className="grid h-[88%]   grid-cols-16  ">
            <Activiybar />
            <Explore />
            <div className={`  col-start-2 col-end-17 md:col-start-6  md:col-end-17 overflow-hidden scroll-smooth ` }>
              <Headermain />
              <div className= {`overflow-y-auto h-screen ` }  style={{ minHeight: '1500 px' }} >{children}</div>
            </div>
          </div>
          <Footer />
        </div>


      </body>

    </html>
  );
}
