import type { Metadata } from "next";

import "./globals.css";

import Header from "../components/Header";
import Footer from "../components/Footer";
import Activiybar from "../components/Activitybar";
import LayoutExplore from "@/components/LayoutExplore";

export const metadata: Metadata = {
  title: "Arezoo Amiri Ayobloo",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased  h-screen w-screen">
        <div className="  grid grid-rows-12 w-screen h-screen overflow-hidden  text-fontcolor">
          <Header />
          <div className="grid row-start-2 row-end-12  overflow-hidden  grid-cols-6 md:flex w-full h-full    ">
            <Activiybar />
            <LayoutExplore >{children}</LayoutExplore>
            
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
